create table DOCGIA
(
    MADOCGIA  NUMBER generated as identity --tạo sequence tự động tăng mà không cần gọi phương thức .nextVal. tham khảo https://www.oracletutorial.com/oracle-sequence/oracle-create-sequence/
        constraint MEMBER_PK
            primary key,
    HODOCGIA  VARCHAR2(25),
    TENDOCGIA VARCHAR2(25),
    SDT       VARCHAR2(15),
    EMAIL     VARCHAR2(50)
)
/

create table TUASACH
(
    MATUASACH  NUMBER generated as identity
        constraint TUASACH_PK
            primary key,
    TENTUASACH VARCHAR2(100),
    TENTHELOAI VARCHAR2(50),
    TACGIA     VARCHAR2(50),
    NXB        VARCHAR2(50),
    SOLUONG    NUMBER
)
/

create table CUONSACH
(
    MACUONSACH NUMBER generated as identity
        constraint CUONSACH_PK
            primary key,
    MATUASACH  NUMBER
        constraint CUONSACH_TUASACH_FK
            references TUASACH,
    TRANGTHAI  VARCHAR2(25)
)
/

create table PHIEUMUONSACH
(
    MAPHIEUMUON   NUMBER generated as identity
        constraint PHIEUMUONSACH_PK
            primary key,
    MADOCGIA      NUMBER
        constraint PHIEUMUONSACH_DOCGIA_FK
            references DOCGIA,
    MACUONSACH    NUMBER
        constraint PHIEUMUONSACH_CUONSACH_FK
            references CUONSACH,
    NGAYMUONSACH  DATE,
    NGAYDUKIENTRA DATE,
    TRANGTHAIPMS  VARCHAR2(25)
)
/

create table PHIEUTRASACH
(
    MAPHIEUTRA   NUMBER generated as identity
        constraint PHIEUTRASACH_PK
            primary key,
    MAPHIEUMUON  NUMBER
        constraint PHIEUTRASACH_PHIEUMUONSACH_FK
            references PHIEUMUONSACH,
    MADOCGIA     NUMBER
        constraint PHIEUTRASACH_DOCGIA_FK
            references DOCGIA,
    MACUONSACH   NUMBER
        constraint PHIEUTRASACH_CUONSACH_FK
            references CUONSACH,
    NGAYTRASACH  DATE,
    SONGAYMUON   NUMBER,
    SONGAYTRATRE NUMBER,
    TIENPHAT     NUMBER(19)
)
/

create table PHIEUPHAT
(
    MAPHIEUPHAT NUMBER(5) generated as identity
        constraint PHIEUPHAT_PK
            primary key,
    MADOCGIA    NUMBER(5)
        constraint PHIEUPHAT_DOCGIA_FK
            references DOCGIA,
    MAPHIEUTRA  NUMBER(5)
        constraint PHIEUPHAT_PHIEUTRASACH_FK
            references PHIEUTRASACH,
    TIENPHAT    NUMBER(19)
)
/

--DOCGIA
INSERT INTO QLTV0804.DOCGIA (HODOCGIA, TENDOCGIA, SDT, EMAIL) VALUES ('Trần Xuân', 'Hạnh', '0358871299', 'hanh@gmail.com');
INSERT INTO QLTV0804.DOCGIA (HODOCGIA, TENDOCGIA, SDT, EMAIL) VALUES ('Trần Phú', 'Thoại', '0412587295', 'thoai@gmail.com');
INSERT INTO QLTV0804.DOCGIA (HODOCGIA, TENDOCGIA, SDT, EMAIL) VALUES ('Phan Minh', 'Quân', '0454876857', 'quanphan@gmail.com');
INSERT INTO QLTV0804.DOCGIA (HODOCGIA, TENDOCGIA, SDT, EMAIL) VALUES ('Đàm Quang', 'Thành', '0936428944', 'thanhqnt@gmail.com');
INSERT INTO QLTV0804.DOCGIA (HODOCGIA, TENDOCGIA, SDT, EMAIL) VALUES ('Đỗ Thị Huyền', 'Trang', '0124587229', 'trangdo@gmail.com');
INSERT INTO QLTV0804.DOCGIA (HODOCGIA, TENDOCGIA, SDT, EMAIL) VALUES ('Trương Quang', 'Ninh', '0246438385', 'ninhtruong@gmaill.com');
INSERT INTO QLTV0804.DOCGIA (HODOCGIA, TENDOCGIA, SDT, EMAIL) VALUES ('Võ Trần Nhật', 'Minh', '0145345598', 'nhatminh@hotmail.com');
INSERT INTO QLTV0804.DOCGIA (HODOCGIA, TENDOCGIA, SDT, EMAIL) VALUES ('Nguyễn Văn', 'Phú', '0124587348', 'phunguyen@gmail.com');
INSERT INTO QLTV0804.DOCGIA (HODOCGIA, TENDOCGIA, SDT, EMAIL) VALUES ('Nguyễn Đăng', 'Quang', '0248594467', 'quang@hotmail.com');
INSERT INTO QLTV0804.DOCGIA (HODOCGIA, TENDOCGIA, SDT, EMAIL) VALUES ('Lương Ngọc', 'Thư', '0345873398', 'ngocthu@gmail.com');
INSERT INTO QLTV0804.DOCGIA (HODOCGIA, TENDOCGIA, SDT, EMAIL) VALUES ('Phạm Đình', 'Sỹ', '0246683492', 'sypham@gmail.com');
INSERT INTO QLTV0804.DOCGIA (HODOCGIA, TENDOCGIA, SDT, EMAIL) VALUES ('Nguyễn Việt ', 'Long', '0134498764', 'longviet@gmail.com');
INSERT INTO QLTV0804.DOCGIA (HODOCGIA, TENDOCGIA, SDT, EMAIL) VALUES ('Nguyễn Tuấn ', 'Kiệt', '0416598693', 'tuankiet@hotmail.com');
INSERT INTO QLTV0804.DOCGIA (HODOCGIA, TENDOCGIA, SDT, EMAIL) VALUES ('Trần Minh', 'Thư', '0245587319', 'minthu@gmail.com');
INSERT INTO QLTV0804.DOCGIA (HODOCGIA, TENDOCGIA, SDT, EMAIL) VALUES ('Nguyễn Thị Hồng ', 'Đào', '0418253823', 'hongdao@hotmail.com');
INSERT INTO QLTV0804.DOCGIA (HODOCGIA, TENDOCGIA, SDT, EMAIL) VALUES ('Nguyễn Ngọc Gia', 'Văn', '0214587254', 'giavan@gmail.com');
INSERT INTO QLTV0804.DOCGIA (HODOCGIA, TENDOCGIA, SDT, EMAIL) VALUES ('Lương Thúy ', 'Vy', '0348729483', 'vyluong@gmail.com');
INSERT INTO QLTV0804.DOCGIA (HODOCGIA, TENDOCGIA, SDT, EMAIL) VALUES ('Phạm Lê Anh', 'Tuấn', '0358267591', 'anhtuan@gmail.com');
INSERT INTO QLTV0804.DOCGIA (HODOCGIA, TENDOCGIA, SDT, EMAIL) VALUES ('Nguyễn Thị Thúy', 'Hiền', '0148504874', 'thuyhien@gmail.com');
INSERT INTO QLTV0804.DOCGIA (HODOCGIA, TENDOCGIA, SDT, EMAIL) VALUES ('Phạm Đình', 'San', '0448788396', 'san@gmail.com');
INSERT INTO QLTV0804.DOCGIA (HODOCGIA, TENDOCGIA, SDT, EMAIL) VALUES ('Vũ Sao', 'Mai', '0458944195', 'saomai@gmail.com');
INSERT INTO QLTV0804.DOCGIA (HODOCGIA, TENDOCGIA, SDT, EMAIL) VALUES ('Nguyễn Ngọc', 'Hải', '0471844872', 'hai@gmail.com');
INSERT INTO QLTV0804.DOCGIA (HODOCGIA, TENDOCGIA, SDT, EMAIL) VALUES ('Võ Thị Phương', 'Dung', '0418495729', 'dungvo@gmail.com');
INSERT INTO QLTV0804.DOCGIA (HODOCGIA, TENDOCGIA, SDT, EMAIL) VALUES ('Nguyễn Duy', 'Thông', '0448274829', 'duythong@gmail.com');
INSERT INTO QLTV0804.DOCGIA (HODOCGIA, TENDOCGIA, SDT, EMAIL) VALUES ('Nguyễn Triệu ', 'Huỳnh', '0458692781', 'huynh@gmail.com');
INSERT INTO QLTV0804.DOCGIA (HODOCGIA, TENDOCGIA, SDT, EMAIL) VALUES ('Phạm Yến', 'Phương', '0248573281', 'yenphuong@gmail.com');
INSERT INTO QLTV0804.DOCGIA (HODOCGIA, TENDOCGIA, SDT, EMAIL) VALUES ('Nguyễn Hữu', 'Thắng', '0418590285', 'huuthang@gmail.com');
INSERT INTO QLTV0804.DOCGIA (HODOCGIA, TENDOCGIA, SDT, EMAIL) VALUES ('Trần Thị Thùy', 'Duyên', '0458719485', 'duyentran@gmail.com');
INSERT INTO QLTV0804.DOCGIA (HODOCGIA, TENDOCGIA, SDT, EMAIL) VALUES ('Phạm Văn', 'Tiến', '0417589247', 'tien@gmail.com');
INSERT INTO QLTV0804.DOCGIA (HODOCGIA, TENDOCGIA, SDT, EMAIL) VALUES ('Lê Văn', 'Dương', '0418573474', 'duongle@gmail.com');
INSERT INTO QLTV0804.DOCGIA (HODOCGIA, TENDOCGIA, SDT, EMAIL) VALUES ('Thái Thanh', 'Nam', '0458713498', 'namthaithanh@gmail.com');
INSERT INTO QLTV0804.DOCGIA (HODOCGIA, TENDOCGIA, SDT, EMAIL) VALUES ('Lê Quốc', 'Bảo', '0455873292', 'quocbao@gmail.com');
INSERT INTO QLTV0804.DOCGIA (HODOCGIA, TENDOCGIA, SDT, EMAIL) VALUES ('Trương Thị Phương', 'Thảo', '0417592410', 'thaotruong@gmail.com');
INSERT INTO QLTV0804.DOCGIA (HODOCGIA, TENDOCGIA, SDT, EMAIL) VALUES ('Nguyễn Hồng', 'Sương', '0148592871', 'suong@gmail.com');
INSERT INTO QLTV0804.DOCGIA (HODOCGIA, TENDOCGIA, SDT, EMAIL) VALUES ('Nguyễn Đình Xuân', 'Phước', '0418549821', 'phuocnguyen@gmail.com');
INSERT INTO QLTV0804.DOCGIA (HODOCGIA, TENDOCGIA, SDT, EMAIL) VALUES ('Nguyễn Hoàng', 'Lâm', '0149598312', 'hoanglam@gmail.com');
INSERT INTO QLTV0804.DOCGIA (HODOCGIA, TENDOCGIA, SDT, EMAIL) VALUES ('Mai Xuân', 'Hoan', '0448691283', 'xuanhoan@gmail.com');
INSERT INTO QLTV0804.DOCGIA (HODOCGIA, TENDOCGIA, SDT, EMAIL) VALUES ('Hoàng Trung', 'Hiếu', '0489381818', 'hieuhoang@gmail.com');
INSERT INTO QLTV0804.DOCGIA (HODOCGIA, TENDOCGIA, SDT, EMAIL) VALUES ('Nguyễn Thị Hồng', 'Bích', '0349782312', 'bichnguyen@gmail.com');
INSERT INTO QLTV0804.DOCGIA (HODOCGIA, TENDOCGIA, SDT, EMAIL) VALUES ('Thái Quang', 'Hưng', '0458712374', 'quanghung@gmail.com');


-- TUASACH
INSERT INTO QLTV0804.TUASACH (TENTUASACH, TENTHELOAI, TACGIA, NXB, SOLUONG) VALUES ('Nhập môn lập trình NMLT', 'Giáo trình', 'Nguyễn Tấn Trần Minh Khang', 'ĐHQG TPHCM', 15);
INSERT INTO QLTV0804.TUASACH (TENTUASACH, TENTHELOAI, TACGIA, NXB, SOLUONG) VALUES ('Phân tích thiết kế Hệ thống thông tin', 'Giáo trình', 'Cao Thị Nhạn', 'ĐHQG TPHCM', 11);
INSERT INTO QLTV0804.TUASACH (TENTUASACH, TENTHELOAI, TACGIA, NXB, SOLUONG) VALUES ('Cơ sở dữ liệu', 'Giáo trình', 'Đỗ Phúc', 'ĐHQG TPHCM', 10);
INSERT INTO QLTV0804.TUASACH (TENTUASACH, TENTHELOAI, TACGIA, NXB, SOLUONG) VALUES ('Nhập môn công nghệ phần mềm', 'Giáo trình', 'Đỗ Văn Nhơn', 'ĐHQG TPHCM', 5);
INSERT INTO QLTV0804.TUASACH (TENTUASACH, TENTHELOAI, TACGIA, NXB, SOLUONG) VALUES ('Nhập môn trí tuệ nhân tạo', 'Giáo trình', 'Hoàng Kiếm, Đinh Nguyễn Anh Dũng', 'ĐHQG TPHCM', 4);
INSERT INTO QLTV0804.TUASACH (TENTUASACH, TENTHELOAI, TACGIA, NXB, SOLUONG) VALUES ('Phân tích dữ liệu lớn', 'Giáo trình', 'Đỗ Phúc', 'ĐHQG TPHCM', 5);
INSERT INTO QLTV0804.TUASACH (TENTUASACH, TENTHELOAI, TACGIA, NXB, SOLUONG) VALUES ('Hệ điều hành Linux ', 'Giáo trình', 'Nguyễn Anh Tuấn', 'ĐHQG TPHCM', 4);
INSERT INTO QLTV0804.TUASACH (TENTUASACH, TENTHELOAI, TACGIA, NXB, SOLUONG) VALUES ('Thiết kế lý luận số', 'Giáo trình', 'Lâm Đức Khải', 'ĐHQG TPHCM', 3);
INSERT INTO QLTV0804.TUASACH (TENTUASACH, TENTHELOAI, TACGIA, NXB, SOLUONG) VALUES ('Đại số tuyến tính ', 'Giáo trình', 'Cao Thanh Tình', 'ĐHQG TPHCM', 8);
INSERT INTO QLTV0804.TUASACH (TENTUASACH, TENTHELOAI, TACGIA, NXB, SOLUONG) VALUES ('Giáo trình Tư tưởng Hồ Chí Minh', 'Giáo trình', 'Bộ giáo dục và Đào tạo', 'Chính trị Quốc gia', 5);
INSERT INTO QLTV0804.TUASACH (TENTUASACH, TENTHELOAI, TACGIA, NXB, SOLUONG) VALUES ('C++ for dummies', 'Tài liệu tham khảo', 'Stephen Randy Davis', 'Nước Ngoài', 6);
INSERT INTO QLTV0804.TUASACH (TENTUASACH, TENTHELOAI, TACGIA, NXB, SOLUONG) VALUES ('Mastering Visual C#.Net', 'Tài liệu tham khảo', 'Jason Price', 'Tổng hợp TPHCM', 6);
INSERT INTO QLTV0804.TUASACH (TENTUASACH, TENTHELOAI, TACGIA, NXB, SOLUONG) VALUES ('101 thủ thuật hay nhất Window 7', 'Khoa học công nghệ – Kinh tế', 'Đoàn Khắc Độ', 'ĐHQG TPHCM', 5);
INSERT INTO QLTV0804.TUASACH (TENTUASACH, TENTHELOAI, TACGIA, NXB, SOLUONG) VALUES ('Vũ trụ trong vỏ hạt dẻ', 'Khoa học công nghệ – Kinh tế', 'Stephen Hawing', 'ĐHQG Hà Nội', 6);
INSERT INTO QLTV0804.TUASACH (TENTUASACH, TENTHELOAI, TACGIA, NXB, SOLUONG) VALUES ('C++ và lập trình hướng đối tượng', 'Tài liệu tham khảo', 'Phạm Văn Ất', 'ĐHQG TPHCM', 7);
INSERT INTO QLTV0804.TUASACH (TENTUASACH, TENTHELOAI, TACGIA, NXB, SOLUONG) VALUES ('13 nguyễn tắc nghĩ giàu, làm giàu', 'Khác', 'Napoleon Hill', 'Trẻ', 3);
INSERT INTO QLTV0804.TUASACH (TENTUASACH, TENTHELOAI, TACGIA, NXB, SOLUONG) VALUES ('Sức hút lãnh đạo', 'Khác', 'Haney Bud', 'Trẻ', 5);
INSERT INTO QLTV0804.TUASACH (TENTUASACH, TENTHELOAI, TACGIA, NXB, SOLUONG) VALUES ('Kỹ thuật lập trình C: cơ sở và nâng cao', 'Tài liệu tham khảo', 'Phạm Văn Ất', 'ĐHQG TPHCM', 6);
INSERT INTO QLTV0804.TUASACH (TENTUASACH, TENTHELOAI, TACGIA, NXB, SOLUONG) VALUES ('Khoa học và công nghệ nano', 'Khoa học công nghệ – Kinh tế', 'Trương Văn Tân', 'ĐHQG TPHCM', 6);
INSERT INTO QLTV0804.TUASACH (TENTUASACH, TENTHELOAI, TACGIA, NXB, SOLUONG) VALUES ('Đồ họa vi tính', 'Khoa học công nghệ – Kinh tế', 'Nguyễn Quốc Cường', 'Văn hóa - thông tin', 5);
INSERT INTO QLTV0804.TUASACH (TENTUASACH, TENTHELOAI, TACGIA, NXB, SOLUONG) VALUES ('Toán rời rạc', 'Tài liệu tham khảo', 'Nguyễn Hữu Anh (phiên dịch)', 'ĐHQG Hà Nội', 4);
INSERT INTO QLTV0804.TUASACH (TENTUASACH, TENTHELOAI, TACGIA, NXB, SOLUONG) VALUES ('Linux QL', 'Tài liệu tham khảo', 'Roderick W.Smith', 'Nước Ngoài', 6);
INSERT INTO QLTV0804.TUASACH (TENTUASACH, TENTHELOAI, TACGIA, NXB, SOLUONG) VALUES ('JavaFX QL', 'Tài liệu tham khảo', 'Doug Lowe', 'Nước Ngoài', 9);
INSERT INTO QLTV0804.TUASACH (TENTUASACH, TENTHELOAI, TACGIA, NXB, SOLUONG) VALUES ('Ẩn dữ liệu ảnh 3D', 'Luận văn', 'Nguyễn Bảo Bình', 'ĐHQG TPHCM', 3);
INSERT INTO QLTV0804.TUASACH (TENTUASACH, TENTHELOAI, TACGIA, NXB, SOLUONG) VALUES ('Kỹ thuật kiểm thử đột biến', 'Luận văn', 'Hoàng Thị Thanh Thủy', 'ĐHQG TPHCM', 4);
INSERT INTO QLTV0804.TUASACH (TENTUASACH, TENTHELOAI, TACGIA, NXB, SOLUONG) VALUES ('Tìm kiếm tự động văn bản song ngữ Anh - Việt từ Internet', 'Luận văn', 'Ngô Quốc Hưng', 'ĐHQG TPHCM', 4);
INSERT INTO QLTV0804.TUASACH (TENTUASACH, TENTHELOAI, TACGIA, NXB, SOLUONG) VALUES ('Vấn đề biển Đông', 'Khác', 'Nguyễn Ngọc Tường', 'Chính trị Quốc gia', 7);
INSERT INTO QLTV0804.TUASACH (TENTUASACH, TENTHELOAI, TACGIA, NXB, SOLUONG) VALUES ('OOP', 'Giáo trình', 'Phạm Thi Vương', 'ĐHQG TPHCM', 0);
INSERT INTO QLTV0804.TUASACH (TENTUASACH, TENTHELOAI, TACGIA, NXB, SOLUONG) VALUES ('Lập trình hướng đối tượng', 'Giáo trình', 'Anh Dũng', 'ĐHQG TPHCM', 0);
INSERT INTO QLTV0804.TUASACH (TENTUASACH, TENTHELOAI, TACGIA, NXB, SOLUONG) VALUES ('Nhập môn công nghệ phần mềm', 'Giáo trình', 'Đinh Nguyễn Anh Dũng', 'ĐHQG TPHCM', 0);

--CUONSACH
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (1, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (1, 'Đã mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (1, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (1, 'Đã mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (1, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (1, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (1, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (1, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (1, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (1, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (1, 'Đã mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (1, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (1, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (1, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (1, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (2, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (2, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (2, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (2, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (2, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (2, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (2, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (2, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (2, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (2, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (2, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (3, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (3, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (3, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (3, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (3, 'Đã mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (3, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (3, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (3, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (3, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (3, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (4, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (4, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (4, 'Đã mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (4, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (4, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (5, 'Đã mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (5, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (5, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (5, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (6, 'Đã mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (6, 'Đã mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (6, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (6, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (6, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (7, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (7, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (7, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (7, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (8, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (8, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (8, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (9, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (9, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (9, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (9, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (9, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (9, 'Đã mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (9, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (9, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (10, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (10, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (10, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (10, 'Đã mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (10, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (11, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (11, 'Đã mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (11, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (11, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (11, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (11, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (12, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (12, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (12, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (12, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (12, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (12, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (13, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (13, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (13, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (13, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (13, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (14, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (14, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (14, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (14, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (14, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (14, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (15, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (15, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (15, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (15, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (15, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (15, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (15, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (16, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (16, 'Đã mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (16, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (17, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (17, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (17, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (17, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (17, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (18, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (18, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (18, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (18, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (18, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (18, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (19, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (19, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (19, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (19, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (19, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (19, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (20, 'Đã mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (20, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (20, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (20, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (20, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (21, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (21, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (21, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (21, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (22, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (22, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (22, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (22, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (22, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (22, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (23, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (23, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (23, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (23, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (23, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (23, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (23, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (23, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (23, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (24, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (24, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (24, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (25, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (25, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (25, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (25, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (26, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (26, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (26, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (26, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (27, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (27, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (27, 'Đã mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (27, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (27, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (27, 'Chưa mượn');
INSERT INTO QLTV0804.CUONSACH (MATUASACH, TRANGTHAI) VALUES (27, 'Chưa mượn');


-- PHIEUMUONSACH
INSERT INTO QLTV0804.PHIEUMUONSACH (MADOCGIA, MACUONSACH, NGAYMUONSACH, NGAYDUKIENTRA, TRANGTHAIPMS) VALUES (1, 1, TO_DATE('2020-06-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-06-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Đã trả');
INSERT INTO QLTV0804.PHIEUMUONSACH (MADOCGIA, MACUONSACH, NGAYMUONSACH, NGAYDUKIENTRA, TRANGTHAIPMS) VALUES (1, 17, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-07-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Đã trả');
INSERT INTO QLTV0804.PHIEUMUONSACH (MADOCGIA, MACUONSACH, NGAYMUONSACH, NGAYDUKIENTRA, TRANGTHAIPMS) VALUES (1, 28, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-07-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Đã trả');
INSERT INTO QLTV0804.PHIEUMUONSACH (MADOCGIA, MACUONSACH, NGAYMUONSACH, NGAYDUKIENTRA, TRANGTHAIPMS) VALUES (2, 3, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-07-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Đã trả');
INSERT INTO QLTV0804.PHIEUMUONSACH (MADOCGIA, MACUONSACH, NGAYMUONSACH, NGAYDUKIENTRA, TRANGTHAIPMS) VALUES (2, 29, TO_DATE('2020-06-24 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-06-29 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Đã trả');
INSERT INTO QLTV0804.PHIEUMUONSACH (MADOCGIA, MACUONSACH, NGAYMUONSACH, NGAYDUKIENTRA, TRANGTHAIPMS) VALUES (3, 39, TO_DATE('2020-06-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Chưa trả');
INSERT INTO QLTV0804.PHIEUMUONSACH (MADOCGIA, MACUONSACH, NGAYMUONSACH, NGAYDUKIENTRA, TRANGTHAIPMS) VALUES (3, 47, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-07-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Chưa trả');
INSERT INTO QLTV0804.PHIEUMUONSACH (MADOCGIA, MACUONSACH, NGAYMUONSACH, NGAYDUKIENTRA, TRANGTHAIPMS) VALUES (4, 45, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-07-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Đã trả');
INSERT INTO QLTV0804.PHIEUMUONSACH (MADOCGIA, MACUONSACH, NGAYMUONSACH, NGAYDUKIENTRA, TRANGTHAIPMS) VALUES (4, 72, TO_DATE('2020-06-24 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-06-29 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Chưa trả');
INSERT INTO QLTV0804.PHIEUMUONSACH (MADOCGIA, MACUONSACH, NGAYMUONSACH, NGAYDUKIENTRA, TRANGTHAIPMS) VALUES (5, 161, TO_DATE('2020-06-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-06-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Đã trả');
INSERT INTO QLTV0804.PHIEUMUONSACH (MADOCGIA, MACUONSACH, NGAYMUONSACH, NGAYDUKIENTRA, TRANGTHAIPMS) VALUES (5, 85, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-07-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Đã trả');
INSERT INTO QLTV0804.PHIEUMUONSACH (MADOCGIA, MACUONSACH, NGAYMUONSACH, NGAYDUKIENTRA, TRANGTHAIPMS) VALUES (6, 42, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-07-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Chưa trả');
INSERT INTO QLTV0804.PHIEUMUONSACH (MADOCGIA, MACUONSACH, NGAYMUONSACH, NGAYDUKIENTRA, TRANGTHAIPMS) VALUES (6, 46, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-07-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Chưa trả');
INSERT INTO QLTV0804.PHIEUMUONSACH (MADOCGIA, MACUONSACH, NGAYMUONSACH, NGAYDUKIENTRA, TRANGTHAIPMS) VALUES (6, 102, TO_DATE('2020-06-26 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-06-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Chưa trả');
INSERT INTO QLTV0804.PHIEUMUONSACH (MADOCGIA, MACUONSACH, NGAYMUONSACH, NGAYDUKIENTRA, TRANGTHAIPMS) VALUES (7, 73, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-07-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Đã trả');
INSERT INTO QLTV0804.PHIEUMUONSACH (MADOCGIA, MACUONSACH, NGAYMUONSACH, NGAYDUKIENTRA, TRANGTHAIPMS) VALUES (7, 11, TO_DATE('2020-06-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-06-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Chưa trả');
INSERT INTO QLTV0804.PHIEUMUONSACH (MADOCGIA, MACUONSACH, NGAYMUONSACH, NGAYDUKIENTRA, TRANGTHAIPMS) VALUES (11, 31, TO_DATE('2020-06-24 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-06-29 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Chưa trả');
INSERT INTO QLTV0804.PHIEUMUONSACH (MADOCGIA, MACUONSACH, NGAYMUONSACH, NGAYDUKIENTRA, TRANGTHAIPMS) VALUES (11, 63, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-07-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Chưa trả');
INSERT INTO QLTV0804.PHIEUMUONSACH (MADOCGIA, MACUONSACH, NGAYMUONSACH, NGAYDUKIENTRA, TRANGTHAIPMS) VALUES (29, 2, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-07-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Đã trả');
INSERT INTO QLTV0804.PHIEUMUONSACH (MADOCGIA, MACUONSACH, NGAYMUONSACH, NGAYDUKIENTRA, TRANGTHAIPMS) VALUES (21, 4, TO_DATE('2020-06-24 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-06-29 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Chưa trả');
INSERT INTO QLTV0804.PHIEUMUONSACH (MADOCGIA, MACUONSACH, NGAYMUONSACH, NGAYDUKIENTRA, TRANGTHAIPMS) VALUES (22, 5, TO_DATE('2020-06-21 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-06-26 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Đã trả');
INSERT INTO QLTV0804.PHIEUMUONSACH (MADOCGIA, MACUONSACH, NGAYMUONSACH, NGAYDUKIENTRA, TRANGTHAIPMS) VALUES (23, 32, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-07-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Đã trả');
INSERT INTO QLTV0804.PHIEUMUONSACH (MADOCGIA, MACUONSACH, NGAYMUONSACH, NGAYDUKIENTRA, TRANGTHAIPMS) VALUES (14, 19, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-07-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Đã trả');
INSERT INTO QLTV0804.PHIEUMUONSACH (MADOCGIA, MACUONSACH, NGAYMUONSACH, NGAYDUKIENTRA, TRANGTHAIPMS) VALUES (9, 144, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-07-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Đã trả');
INSERT INTO QLTV0804.PHIEUMUONSACH (MADOCGIA, MACUONSACH, NGAYMUONSACH, NGAYDUKIENTRA, TRANGTHAIPMS) VALUES (19, 69, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-07-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Chưa trả');
INSERT INTO QLTV0804.PHIEUMUONSACH (MADOCGIA, MACUONSACH, NGAYMUONSACH, NGAYDUKIENTRA, TRANGTHAIPMS) VALUES (23, 81, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-07-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Đã trả');
INSERT INTO QLTV0804.PHIEUMUONSACH (MADOCGIA, MACUONSACH, NGAYMUONSACH, NGAYDUKIENTRA, TRANGTHAIPMS) VALUES (37, 68, TO_DATE('2020-06-24 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-06-29 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Đã trả');
INSERT INTO QLTV0804.PHIEUMUONSACH (MADOCGIA, MACUONSACH, NGAYMUONSACH, NGAYDUKIENTRA, TRANGTHAIPMS) VALUES (24, 129, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-07-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Đã trả');
INSERT INTO QLTV0804.PHIEUMUONSACH (MADOCGIA, MACUONSACH, NGAYMUONSACH, NGAYDUKIENTRA, TRANGTHAIPMS) VALUES (36, 120, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-07-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Đã trả');
INSERT INTO QLTV0804.PHIEUMUONSACH (MADOCGIA, MACUONSACH, NGAYMUONSACH, NGAYDUKIENTRA, TRANGTHAIPMS) VALUES (39, 118, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-07-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Đã trả');
INSERT INTO QLTV0804.PHIEUMUONSACH (MADOCGIA, MACUONSACH, NGAYMUONSACH, NGAYDUKIENTRA, TRANGTHAIPMS) VALUES (32, 117, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-07-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Đã trả');
INSERT INTO QLTV0804.PHIEUMUONSACH (MADOCGIA, MACUONSACH, NGAYMUONSACH, NGAYDUKIENTRA, TRANGTHAIPMS) VALUES (31, 158, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-07-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Chưa trả');
INSERT INTO QLTV0804.PHIEUMUONSACH (MADOCGIA, MACUONSACH, NGAYMUONSACH, NGAYDUKIENTRA, TRANGTHAIPMS) VALUES (20, 121, TO_DATE('2020-06-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-06-28 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Chưa trả');
INSERT INTO QLTV0804.PHIEUMUONSACH (MADOCGIA, MACUONSACH, NGAYMUONSACH, NGAYDUKIENTRA, TRANGTHAIPMS) VALUES (33, 105, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-07-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Đã trả');
INSERT INTO QLTV0804.PHIEUMUONSACH (MADOCGIA, MACUONSACH, NGAYMUONSACH, NGAYDUKIENTRA, TRANGTHAIPMS) VALUES (17, 91, TO_DATE('2020-06-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-06-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Đã trả');
INSERT INTO QLTV0804.PHIEUMUONSACH (MADOCGIA, MACUONSACH, NGAYMUONSACH, NGAYDUKIENTRA, TRANGTHAIPMS) VALUES (34, 92, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Đã trả');
INSERT INTO QLTV0804.PHIEUMUONSACH (MADOCGIA, MACUONSACH, NGAYMUONSACH, NGAYDUKIENTRA, TRANGTHAIPMS) VALUES (23, 143, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-07-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Đã trả');
INSERT INTO QLTV0804.PHIEUMUONSACH (MADOCGIA, MACUONSACH, NGAYMUONSACH, NGAYDUKIENTRA, TRANGTHAIPMS) VALUES (7, 2, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-07-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Chưa trả');
INSERT INTO QLTV0804.PHIEUMUONSACH (MADOCGIA, MACUONSACH, NGAYMUONSACH, NGAYDUKIENTRA, TRANGTHAIPMS) VALUES (9, 154, TO_DATE('2020-06-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-06-28 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Đã trả');

-- PHIEUTRASACH
INSERT INTO QLTV0804.PHIEUTRASACH (MAPHIEUMUON, MADOCGIA, MACUONSACH, NGAYTRASACH, SONGAYMUON, SONGAYTRATRE, TIENPHAT) VALUES (3, 1, 28, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 0, 0, 0);
INSERT INTO QLTV0804.PHIEUTRASACH (MAPHIEUMUON, MADOCGIA, MACUONSACH, NGAYTRASACH, SONGAYMUON, SONGAYTRATRE, TIENPHAT) VALUES (25, 14, 19, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 0, 0, 0);
INSERT INTO QLTV0804.PHIEUTRASACH (MAPHIEUMUON, MADOCGIA, MACUONSACH, NGAYTRASACH, SONGAYMUON, SONGAYTRATRE, TIENPHAT) VALUES (6, 2, 3, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 0, 0, 0);
INSERT INTO QLTV0804.PHIEUTRASACH (MAPHIEUMUON, MADOCGIA, MACUONSACH, NGAYTRASACH, SONGAYMUON, SONGAYTRATRE, TIENPHAT) VALUES (13, 5, 85, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 0, 0, 0);
INSERT INTO QLTV0804.PHIEUTRASACH (MAPHIEUMUON, MADOCGIA, MACUONSACH, NGAYTRASACH, SONGAYMUON, SONGAYTRATRE, TIENPHAT) VALUES (30, 24, 129, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 0, 0, 0);
INSERT INTO QLTV0804.PHIEUTRASACH (MAPHIEUMUON, MADOCGIA, MACUONSACH, NGAYTRASACH, SONGAYMUON, SONGAYTRATRE, TIENPHAT) VALUES (26, 9, 144, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 0, 0, 0);
INSERT INTO QLTV0804.PHIEUTRASACH (MAPHIEUMUON, MADOCGIA, MACUONSACH, NGAYTRASACH, SONGAYMUON, SONGAYTRATRE, TIENPHAT) VALUES (28, 23, 81, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 0, 0, 0);
INSERT INTO QLTV0804.PHIEUTRASACH (MAPHIEUMUON, MADOCGIA, MACUONSACH, NGAYTRASACH, SONGAYMUON, SONGAYTRATRE, TIENPHAT) VALUES (17, 7, 73, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 0, 0, 0);
INSERT INTO QLTV0804.PHIEUTRASACH (MAPHIEUMUON, MADOCGIA, MACUONSACH, NGAYTRASACH, SONGAYMUON, SONGAYTRATRE, TIENPHAT) VALUES (38, 34, 92, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 0, 0, 0);
INSERT INTO QLTV0804.PHIEUTRASACH (MAPHIEUMUON, MADOCGIA, MACUONSACH, NGAYTRASACH, SONGAYMUON, SONGAYTRATRE, TIENPHAT) VALUES (21, 29, 2, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 0, 0, 0);
INSERT INTO QLTV0804.PHIEUTRASACH (MAPHIEUMUON, MADOCGIA, MACUONSACH, NGAYTRASACH, SONGAYMUON, SONGAYTRATRE, TIENPHAT) VALUES (36, 33, 105, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 0, 0, 0);
INSERT INTO QLTV0804.PHIEUTRASACH (MAPHIEUMUON, MADOCGIA, MACUONSACH, NGAYTRASACH, SONGAYMUON, SONGAYTRATRE, TIENPHAT) VALUES (10, 4, 45, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 0, 0, 0);
INSERT INTO QLTV0804.PHIEUTRASACH (MAPHIEUMUON, MADOCGIA, MACUONSACH, NGAYTRASACH, SONGAYMUON, SONGAYTRATRE, TIENPHAT) VALUES (33, 32, 117, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 0, 0, 0);
INSERT INTO QLTV0804.PHIEUTRASACH (MAPHIEUMUON, MADOCGIA, MACUONSACH, NGAYTRASACH, SONGAYMUON, SONGAYTRATRE, TIENPHAT) VALUES (24, 23, 32, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 0, 0, 0);
INSERT INTO QLTV0804.PHIEUTRASACH (MAPHIEUMUON, MADOCGIA, MACUONSACH, NGAYTRASACH, SONGAYMUON, SONGAYTRATRE, TIENPHAT) VALUES (2, 1, 17, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 0, 0, 0);
INSERT INTO QLTV0804.PHIEUTRASACH (MAPHIEUMUON, MADOCGIA, MACUONSACH, NGAYTRASACH, SONGAYMUON, SONGAYTRATRE, TIENPHAT) VALUES (39, 23, 143, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 0, 0, 0);
INSERT INTO QLTV0804.PHIEUTRASACH (MAPHIEUMUON, MADOCGIA, MACUONSACH, NGAYTRASACH, SONGAYMUON, SONGAYTRATRE, TIENPHAT) VALUES (31, 36, 120, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 0, 0, 0);
INSERT INTO QLTV0804.PHIEUTRASACH (MAPHIEUMUON, MADOCGIA, MACUONSACH, NGAYTRASACH, SONGAYMUON, SONGAYTRATRE, TIENPHAT) VALUES (32, 39, 118, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 0, 0, 0);
INSERT INTO QLTV0804.PHIEUTRASACH (MAPHIEUMUON, MADOCGIA, MACUONSACH, NGAYTRASACH, SONGAYMUON, SONGAYTRATRE, TIENPHAT) VALUES (29, 37, 68, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 6, 1, 1000);
INSERT INTO QLTV0804.PHIEUTRASACH (MAPHIEUMUON, MADOCGIA, MACUONSACH, NGAYTRASACH, SONGAYMUON, SONGAYTRATRE, TIENPHAT) VALUES (7, 2, 29, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 6, 1, 1000);
INSERT INTO QLTV0804.PHIEUTRASACH (MAPHIEUMUON, MADOCGIA, MACUONSACH, NGAYTRASACH, SONGAYMUON, SONGAYTRATRE, TIENPHAT) VALUES (12, 5, 161, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 12, 7, 7000);
INSERT INTO QLTV0804.PHIEUTRASACH (MAPHIEUMUON, MADOCGIA, MACUONSACH, NGAYTRASACH, SONGAYMUON, SONGAYTRATRE, TIENPHAT) VALUES (23, 22, 5, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 9, 4, 4000);
INSERT INTO QLTV0804.PHIEUTRASACH (MAPHIEUMUON, MADOCGIA, MACUONSACH, NGAYTRASACH, SONGAYMUON, SONGAYTRATRE, TIENPHAT) VALUES (37, 17, 91, TO_DATE('2020-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 12, 7, 7000);
INSERT INTO QLTV0804.PHIEUTRASACH (MAPHIEUMUON, MADOCGIA, MACUONSACH, NGAYTRASACH, SONGAYMUON, SONGAYTRATRE, TIENPHAT) VALUES (1, 1, 1, TO_DATE('2020-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 13, 8, 8000);


-- PHIEUPHAT
INSERT INTO QLTV0804.PHIEUPHAT (MADOCGIA, MAPHIEUTRA, TIENPHAT) VALUES (37, 19, 1000);
INSERT INTO QLTV0804.PHIEUPHAT (MADOCGIA, MAPHIEUTRA, TIENPHAT) VALUES (2, 20, 1000);
INSERT INTO QLTV0804.PHIEUPHAT (MADOCGIA, MAPHIEUTRA, TIENPHAT) VALUES (5, 21, 7000);
INSERT INTO QLTV0804.PHIEUPHAT (MADOCGIA, MAPHIEUTRA, TIENPHAT) VALUES (22, 22, 4000);
INSERT INTO QLTV0804.PHIEUPHAT (MADOCGIA, MAPHIEUTRA, TIENPHAT) VALUES (17, 23, 7000);
INSERT INTO QLTV0804.PHIEUPHAT (MADOCGIA, MAPHIEUTRA, TIENPHAT) VALUES (1, 24, 8000);










